### ISSUE TITLE
Use flat headerbar

### ISSUE THREAD

**Issue by Suzie97** [jhaygood86/gotham#3]
# Proposal
Since this is a single window app, without much going on in the headerbar, a flat headerbar would look more modern without sacrificing usability.

# Prior Art
## Mixer
![Screenshot from 2021-09-25 00-34-04](https://user-images.githubusercontent.com/68198116/134727352-af847617-de54-43cb-b137-04f182d1c2c2.png)

## Harvey
![Screenshot from 2021-09-25 00-34-38](https://user-images.githubusercontent.com/68198116/134727390-0e05b967-87b8-4656-91b7-1aec5fddafe3.png)

**Comment by jhaygood86** [comment]
Good idea!

**Comment by jhaygood86** [comment]
I just pushed this change to main.
